### PR TITLE
catalyst.conf and livecd-stage2-template fix typo and whitespace

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Noticed a small typo while going over `/etc/catalyst.conf`, figured I might as well fix it :)
Whilst doing so noticed there was a bunch of odd/double whitespace in it, so fixed that as well.

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Noticed another typo and the same whitespace issues in `examples/livecd-stage2_template.spec`, added fixes for that to this PR as well.

**Comment by simonvanderveldt** [comment]
Any chance this can be reviewed/merged?

**Comment by dol-sen** [comment]
Thank you.  But we did not use the whitespace changes as it is preferred that there are 2 or 3 spaces separating sentences.  It makes it much clearer where sentence breaks are especially with proportional fonts and in technical documentation that often contains abbreviations.   You will find most word processing programs use/recommend multiple spaces automatically when reformatting paragraphs.

**Comment by simonvanderveldt** [comment]
Hmm, I've never seen that so far but OK I guess :)

**Pull request closed without merging**
